### ISSUE TITLE
getDevices() KeyError

### ISSUE THREAD

**Issue by DaveL17** [FlyingDiver/Indigo-MyQ#14]
Request: trap KeyError.

```
Jan 6, 2021 at 5:42:21 AM
   MyQ Error                       Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 86, in runConcurrentThread
  File "plugin.py", line 421, in getDevices
KeyError: 'items'

   MyQ Error                       plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```  

Thanks,
Dave

**Comment by FlyingDiver** [comment]
Fixed in 7.5.3.
