### ISSUE TITLE
Unable to get Devices - getDevices failure, status_code = 400

### ISSUE THREAD

**Issue by ronniesaye** [FlyingDiver/Indigo-MyQ#19]
Hello,

I am unable to get device list. MyQ login works fine.

MacOS 11.2.3
Indigo 7.5.0

Error Code
```
Mar 29, 2021 at 2:24:41 PM
   Loading plugin "MyQ 7.5.3"
   Starting plugin "MyQ 7.5.3" (pid 28621)
   Started plugin "MyQ 7.5.3"
   MyQ                             Starting MyQ
   MyQ Debug                       statusFrequency = 600.0
   MyQ Debug                       myqLogin response = {"SecurityToken":"*********"}
   MyQ Debug                       myqLogin successful
   MyQ Debug                       myqLogin account_info = {u'UserName': u'*****@*****.com', u'Account': {u'Name': u"Ronnie's Home", u'Roles': {u'href': u'http://api.myqdevice.com/api/v5/Accounts/********35e5b4/Roles'}, u'UserAllowance': 4, u'DirectoryCodeLength': 0, u'AccessGroups': {u'href': u'http://api.myqdevice.com/api/v5/Accounts/b310f9f1-bfdc-4d2a-b8cf-96a90535e5b4/AccessGroups'}, u'Devices': {u'href': u'http://api.myqdevice.com/api/v5/Accounts/b310f9f1-bfdc-4d2a-b8cf-96a90535e5b4/Devices'}, u'Id': u'********6a90535e5b4', u'Zones': {u'href': u'http://api.myqdevice.com/api/v5/Accounts/b310f9f1-bfdc-4d2a-b8cf-96a90535e5b4/Zones'}, u'Phone': u'*****', u'href': u'http://api.myqdevice.com/api/v5/Accounts/b310f9f1-bfdc-4d2a-b8cf-96a90535e5b4', u'ContactName': u'Ronnie Saye', u'Address': {u'PostalCode': u'****', u'City': u'******', u'State': u'Texas', u'Country': {u'href': u'http://api.myqdevice.com/api/v5/Countries/USA', u'Code': u'USA', u'IsEEACountry': False}, u'AddressLine1': u'*******'}, u'TimeZone': u'America/Chicago', u'AccessSchedules': {u'href': u'http://api.myqdevice.com/api/v5/Accounts/b310f9f1-bfdc-4d2a-b8cf-96a90535e5b4/AccessSchedules'}, u'Email': u'********', u'Users': {u'href': u'http://api.myqdevice.com/api/v5/Accounts/b310f9f*****5e5b4/Users'}}, u'Users': {u'href': u'http://api.myqdevice.com/api/v5/My/Users'}, u'FirstName': u'Ronnie', u'Admin': False, u'AnalyticsId': u'*******9-a46b-f295025aac5f', u'DiagnosticDataOptIn': False, u'Address': {u'PostalCode': u'*****', u'City': u'******', u'State': u'Texas', u'Country': {u'href': u'http://api.myqdevice.com/api/v5/Countries/USA', u'Code': u'USA', u'IsEEACountry': False}, u'AddressLine1': u'****** ******'}, u'UserId': u'**********9f38-4d72deaa6071', u'RequestAccountLinkInfo': False, u'CultureCode': u'en', u'Phone': u'********', u'LastName': u'****', u'TimeZone': {u'Id': u'America/Chicago', u'Name': u'America/Chicago'}, u'Email': u'*****@****', u'MailingListOptIn': False}
   MyQ Warning                     getDevices failure, status_code = 400
```

**Comment by FlyingDiver** [comment]
I suspect that you're now getting bit by the same API changes that are effecting many users.  The only solution is to try this beta version:  https://github.com/FlyingDiver/Indigo-MyQ/releases/tag/7.6.0

Read the release notes carefully, this is not a drop in replacement.

**Comment by FlyingDiver** [comment]
Did you try 7.6.0?  Does it work?

**Comment by ronniesaye** [comment]
It does not work. Thanks for checking.

Thanks,

Ronnie Saye

**Comment by FlyingDiver** [comment]
I'm going to need the logs from the new version to investigate further.  Please post them directly to GitHub, don't use email (it messes up the text).

**Comment by mlamoure** [comment]
Hey @FlyingDiver - I think I did the pip3 install commands correct, but I'm occasionally getting this:

```
Apr 5, 2021 at 3:27:57 PM
   MyQ Error                       Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 86, in runConcurrentThread
  File "plugin.py", line 153, in requestUpdate
  File "plugin.py", line 97, in pymyq_write
IOError: [Errno 32] Broken pipe

   MyQ Error                       plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

```

**Comment by FlyingDiver** [comment]
Hmm.  That means it can't communicate with the sub-process running the Python3 code.  Do this - restart the plugin in an interactive shell:

<img width="517" alt="Screen Shot 2021-04-05 at 3 34 11 PM" src="https://user-images.githubusercontent.com/72976/113617575-7c1a0080-9624-11eb-81dd-480d5e0b5f4f.png">

It'll open a Terminal window on the Indigo server.  Let it run until you get the error, then post the contents of the Terminal session here.  It'll start like this:

```
Starting shell for plugin MyQ.indigoPlugin.
To access the plugin instance use the global named self.

Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Connected to Indigo Server v7.5.0, api v2.4 (localhost:1176)
Started Plugin MyQ v7.6.0
>>> 


```

**Comment by FlyingDiver** [comment]
Unfortunately, that's the only way to see errors from the sub-process.

**Comment by mlamoure** [comment]
Pretty neat, I never knew about that (and, I develop plugins).

Here's what happened:

```


Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Connected to Indigo Server v7.5.0, api v2.4 (localhost:1176)
Started Plugin MyQ v7.6.0
>>> /Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/MyQ.indigoPlugin/Contents/Server Plugin/py3myq/pymyq/api.py:452: RuntimeWarning: coroutine 'API._authenticate' was never awaited
  self._authenticate(), name="MyQ_Authenticate"
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "./py3myq/wrapper.py", line 119, in <module>
    asyncio.run(main(sys.argv))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./py3myq/wrapper.py", line 29, in main
    api = await login(sys.argv[1], sys.argv[2], websession)
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/MyQ.indigoPlugin/Contents/Server Plugin/py3myq/pymyq/api.py", line 648, in login
    await api.authenticate(wait=True)
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/MyQ.indigoPlugin/Contents/Server Plugin/py3myq/pymyq/api.py", line 452, in authenticate
    self._authenticate(), name="MyQ_Authenticate"
TypeError: create_task() got an unexpected keyword argument 'name'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "plugin.py", line 105, in pymyq_read
    data = json.loads(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mlamoure** [comment]
And the indigo log:

`
Started plugin "MyQ 7.6.0"
   MyQ                             Starting MyQ
   MyQ Debug                       statusFrequency = 600.0
   MyQ Debug                       Garage Door: deviceStartComm: Device version is up to date (2)
   MyQ Debug                       Garage Door: deviceStartComm: Adding device (1969968999) to MyQ device list
`

**Comment by FlyingDiver** [comment]
There's way too many quoting levels in that terminal output.  Please post directly.

**Comment by FlyingDiver** [comment]
And please verify the Python 3 version on that system.

**Comment by mlamoure** [comment]
I've tried to format it a few times, best I could do.  This was direct using GitHub in browser.

mini:~ mike$ python3 --version
Python 3.7.3

**Comment by FlyingDiver** [comment]
You need to be have Python 3.8.X as the readme says.  Get that updated (latest version of Xcode, I think), and see if that fixes it.

**Comment by mlamoure** [comment]
Will try that out, sorry for not seeing that 3.8 was required.

**Comment by mlamoure** [comment]
I updated to Python 3.8 and restarted Indigo.  Oddly enough experiencing the exact same error.

```
Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Connected to Indigo Server v7.5.0, api v2.4 (localhost:1176)
Started Plugin MyQ v7.6.0
>>> /Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/MyQ.indigoPlugin/Contents/Server Plugin/py3myq/pymyq/api.py:452: RuntimeWarning: coroutine 'API._authenticate' was never awaited
  self._authenticate(), name="MyQ_Authenticate"
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "./py3myq/wrapper.py", line 119, in <module>
    asyncio.run(main(sys.argv))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./py3myq/wrapper.py", line 29, in main
    api = await login(sys.argv[1], sys.argv[2], websession)
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/MyQ.indigoPlugin/Contents/Server Plugin/py3myq/pymyq/api.py", line 648, in login
    await api.authenticate(wait=True)
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/MyQ.indigoPlugin/Contents/Server Plugin/py3myq/pymyq/api.py", line 452, in authenticate
    self._authenticate(), name="MyQ_Authenticate"
TypeError: create_task() got an unexpected keyword argument 'name'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "plugin.py", line 105, in pymyq_read
    data = json.loads(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mlamoure** [comment]
mini:~ mike$ python3 --version
Python 3.8.9

**Comment by FlyingDiver** [comment]
Make sure all the Python3 packages are up to date.  I suspect you have some older (pre-3.8.x) packages, as that error is coming from one of the asyncio packages.

Try: pip3 list --outdated

I have:

aiofiles           0.6.0
aiohttp            3.7.3
beautifulsoup4     4.9.3
bs4                0.0.1
pkce               1.0.2

**Comment by ronniesaye** [comment]
Sorry for the delay. I just install 7.6 and all is working. Thank you.

Thanks,

Ronnie Saye
