### ISSUE TITLE
Unknown Error Using Plugin

### ISSUE THREAD

**Issue by pgpappas** [FlyingDiver/Indigo-MyQ#27]
I can't get the plugin to work in Indigo V2021.2. I'm using MacOS 12.2.1. My model is Liftmaster 8500W. I am also using a MyQ-Home Bridge with my opener paired to the hub. The myQ app works and HomeKit works. The myQ plugin shows the following errors.
 MyQ Error                       Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 86, in runConcurrentThread
  File "plugin.py", line 153, in requestUpdate
  File "plugin.py", line 97, in pymyq_write
IOError: [Errno 32] Broken pipe

   MyQ Error                       plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

Your help would be appreciated.

**Comment by FlyingDiver** [comment]
Will not be fixed in this plugin version.  The Python3 plugin for 2022.1 does not have this issue.

**Comment by pgpappas** [comment]
I'm still having issues. I now have a new error since updating Indigo and your plugin to version 2022.1. I get the following errors trying to lock and unlock the garage door.

May 13, 2022 at 11:36:01 AM
   MyQ Error                       Error in plugin execution ExecuteAction:

  File "plugin.py", line 320, in actionControlDevice
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
  File "plugin.py", line 424, in pymyq_open
type: ''

   MyQ Error                       Error in plugin execution ExecuteAction:

  File "plugin.py", line 324, in actionControlDevice
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
  File "plugin.py", line 452, in pymyq_close
type: ''

What did I do wrong?
