### ISSUE TITLE
Error when trying to edit/recreate device

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-MyQ#5]
https://forums.indigodomo.com/viewtopic.php?f=214&t=2209

**Comment by FlyingDiver** [comment]
Change device type from MyQ to something else and back again.  Address field is lost.

```
   MyQ                             Starting MyQ
   MyQ Debug                       statusFrequency = 900.0
   MyQ Debug                       deviceStartComm: Large Garage Door (CG0838484818): Device Version is up to date
   MyQ Debug                       deviceStartComm: Adding Device Large Garage Door (CG0838484818) (520259575) to MyQ device list
   MyQ Debug                       deviceStartComm: Small Garage Door (CG0838484821): Device Version is up to date
   MyQ Debug                       deviceStartComm: Adding Device Small Garage Door (CG0838484821) (702772387) to MyQ device list
   MyQ Debug                       myqLogin successful
   MyQ Debug                       getDevices: 3 Devices
   MyQ Debug                       getDevices: MyQDeviceTypeId = 1, MyQDeviceTypeName = Gateway, DeviceId = 9242760
   MyQ Debug                       getDevices: MyQDeviceTypeId = 2, MyQDeviceTypeName = GarageDoorOpener, DeviceId = 9242856
   MyQ Debug                       Checking Opener Device: Large Garage Door (CG0838484818) () against 9242856
   MyQ Error                       Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 85, in runConcurrentThread
  File "plugin.py", line 407, in getDevices
ValueError: invalid literal for int() with base 10: ''

   MyQ Error                       plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

**Comment by FlyingDiver** [comment]
```
address : 
batteryLevel : None
buttonGroupCount : 0
configured : True
description : Opener Device auto-created by MyQ plugin from gateway information
deviceTypeId : myqOpener
displayStateId : onOffState
displayStateImageSel : Unlocked
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 0
globalProps : MetaProps : (dict)
     com.flyingdiver.indigoplugin.myq : (dict)
          IsLockSubType : true (bool)
          address :  (string)
          devVersCount : 1 (integer)
          sensor :  (string)
     emptyDict : (dict)
id : 520259575
lastChanged : 2019-02-13 20:57:34
lastSuccessfulComm : 2019-02-13 20:57:34
ledStates : []
model : MyQ Door Opener
name : Large Garage Door (CG0838484818)
onState : False
ownerProps : com.flyingdiver.indigoplugin.myq : (dict)
     IsLockSubType : true (bool)
     address :  (string)
     devVersCount : 1 (integer)
     sensor :  (string)
pluginId : com.flyingdiver.indigoplugin.myq
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     doorStatus : 0 (integer)
     doorStatus.Closed : false (bool)
     doorStatus.Closing : false (bool)
     doorStatus.Disconnected : false (bool)
     doorStatus.Open : false (bool)
     doorStatus.Opening : false (bool)
     doorStatus.Stopped : false (bool)
     doorStatus.Unknown : false (bool)
     onOffState : off (on/off bool)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None
```

**Comment by FlyingDiver** [comment]
Address information is lost.  Need to rework plugin to allow user to re-select by address from known list.

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-MyQ/releases/tag/7.3.0
